FROM node:22-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @workspace/apatris-dashboard... build

FROM nginx:stable-alpine
COPY --from=builder /app/artifacts/apatris-dashboard/dist /usr/share/nginx/html
RUN sed -i '10i \    location / { try_files $uri $uri/ /index.html; }' /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
