FROM node:20-slim AS builder
RUN corepack enable
WORKDIR /app
COPY . .
# We disable the "frozen-lockfile" check to let pnpm fix the map on the fly
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter apatris-dashboard build

FROM node:20-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/artifacts/apatris-dashboard/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
