kind = "web"
previewPath = "/eej-mobile/"
title = "EEJ Mobile App"
version = "1.0.0"
id = "artifacts/eej-mobile"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 19578
name = "web"
paths = ["/eej-mobile/"]

[services.development]
run = "pnpm --filter @workspace/eej-mobile run dev"

[services.env]
PORT = "19578"
BASE_PATH = "/eej-mobile/"

[services.production]
build = ["pnpm", "--filter", "@workspace/eej-mobile", "run", "build"]
publicDir = "artifacts/eej-mobile/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
