import type { Worker } from "./compliance.js";

const today = new Date();
const daysFromNow = (d: number) => {
  const dt = new Date(today);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString().split("T")[0];
};

export const MOCK_WORKERS: Worker[] = [
  {
    id: "mock-001",
    name: "Aleksander Nowak",
    specialization: "TIG",
    trcExpiry: daysFromNow(8),
    workPermitExpiry: daysFromNow(120),
    bhpStatus: daysFromNow(-5),
    contractEndDate: daysFromNow(60),
    email: "a.nowak@example.com",
    phone: "+48 601 234 567",
    complianceStatus: "critical",
    daysUntilNextExpiry: 8,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "8",
    highestQualification: "Bachelor",
    siteLocation: "Amazon Logistics",
    totalHours: 342.5,
  },
  {
    id: "mock-002",
    name: "Marta Kowalski",
    specialization: "Nurse",
    trcExpiry: daysFromNow(45),
    workPermitExpiry: daysFromNow(200),
    bhpStatus: daysFromNow(45),
    contractEndDate: daysFromNow(180),
    email: "m.kowalski@example.com",
    phone: "+48 501 987 654",
    complianceStatus: "warning",
    daysUntilNextExpiry: 45,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "5",
    highestQualification: "Master",
    siteLocation: "Berlin Hospital",
    totalHours: 128,
  },
  {
    id: "mock-003",
    name: "Vasile Popescu",
    specialization: "MIG",
    trcExpiry: daysFromNow(180),
    workPermitExpiry: daysFromNow(300),
    bhpStatus: daysFromNow(90),
    contractEndDate: daysFromNow(240),
    email: "v.popescu@example.com",
    phone: "+40 721 456 789",
    complianceStatus: "compliant",
    daysUntilNextExpiry: 90,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "12",
    highestQualification: "Diploma",
    siteLocation: "Amazon Logistics",
    totalHours: 670,
  },
  {
    id: "mock-004",
    name: "Irina Petrescu",
    specialization: "Teacher",
    trcExpiry: daysFromNow(20),
    workPermitExpiry: daysFromNow(20),
    bhpStatus: daysFromNow(55),
    contractEndDate: daysFromNow(90),
    email: "i.petrescu@example.com",
    phone: "+40 754 321 000",
    complianceStatus: "critical",
    daysUntilNextExpiry: 20,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "3",
    highestQualification: "Bachelor",
    siteLocation: "Munich Academy",
    totalHours: 88,
  },
  {
    id: "mock-005",
    name: "Dmitro Kovalenko",
    specialization: "MAG",
    trcExpiry: daysFromNow(400),
    workPermitExpiry: daysFromNow(365),
    bhpStatus: daysFromNow(200),
    contractEndDate: daysFromNow(300),
    email: "d.kovalenko@example.com",
    phone: "+380 67 891 2345",
    complianceStatus: "compliant",
    daysUntilNextExpiry: 200,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "7",
    highestQualification: "Diploma",
    siteLocation: null,
    totalHours: 215,
  },
  {
    id: "mock-006",
    name: "Bogdan Ionescu",
    specialization: "FABRICATOR",
    trcExpiry: daysFromNow(-10),
    workPermitExpiry: daysFromNow(90),
    bhpStatus: "Active",
    contractEndDate: null,
    email: "b.ionescu@example.com",
    phone: "+40 766 555 333",
    complianceStatus: "non-compliant",
    daysUntilNextExpiry: null,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "15",
    highestQualification: "Diploma",
    siteLocation: "Berlin Hospital",
    totalHours: 1120.5,
  },
  {
    id: "mock-007",
    name: "Ana-Maria Stan",
    specialization: "Engineer",
    trcExpiry: daysFromNow(60),
    workPermitExpiry: daysFromNow(410),
    bhpStatus: daysFromNow(180),
    contractEndDate: daysFromNow(365),
    email: "a.stan@example.com",
    phone: "+40 722 111 999",
    complianceStatus: "warning",
    daysUntilNextExpiry: 60,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "9",
    highestQualification: "Master",
    siteLocation: "Munich Academy",
    totalHours: 304,
  },
  {
    id: "mock-008",
    name: "Tomasz Wieczorek",
    specialization: "MMA",
    trcExpiry: daysFromNow(250),
    workPermitExpiry: daysFromNow(250),
    bhpStatus: daysFromNow(120),
    contractEndDate: daysFromNow(200),
    email: "t.wieczorek@example.com",
    phone: "+48 512 777 666",
    complianceStatus: "compliant",
    daysUntilNextExpiry: 120,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "6",
    highestQualification: "Bachelor",
    siteLocation: null,
    totalHours: null,
  },
  {
    id: "mock-009",
    name: "Catalin Dumitrescu",
    specialization: "IT Specialist",
    trcExpiry: null,
    workPermitExpiry: daysFromNow(500),
    bhpStatus: "Active",
    contractEndDate: daysFromNow(730),
    email: "c.dumitrescu@example.com",
    phone: "+40 744 888 222",
    complianceStatus: "compliant",
    daysUntilNextExpiry: null,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "11",
    highestQualification: "Bachelor",
    siteLocation: "Amazon Logistics",
    totalHours: 520,
  },
  {
    id: "mock-010",
    name: "Olga Marchenko",
    specialization: "Logistics",
    trcExpiry: daysFromNow(12),
    workPermitExpiry: daysFromNow(30),
    bhpStatus: daysFromNow(12),
    contractEndDate: daysFromNow(60),
    email: "o.marchenko@example.com",
    phone: "+380 50 123 4567",
    complianceStatus: "critical",
    daysUntilNextExpiry: 12,
    passportAttachments: [],
    contractAttachments: [],
    yearsOfExperience: "4",
    highestQualification: "Diploma",
    siteLocation: null,
    totalHours: 67.5,
  },
];

export function isMockMode(): boolean {
  return !process.env.AIRTABLE_API_KEY;
}

export function getMockWorker(id: string): Worker | undefined {
  return MOCK_WORKERS.find((w) => w.id === id);
}
