import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import workersRouter from "./workers.js";
import authRouter from "./auth.js";
import adminRouter from "./admin.js";
import complianceRouter from "./compliance.js";
import portalRouter from "./portal.js";
import auditRouter from "./audit.js";
import payrollRouter from "./payroll.js";
import clientsRouter from "./clients.js";
import { twofaRouter } from "./twofa.js";
import notificationsRouter from "./notifications.js";
import workerNotesRouter from "./worker-notes.js";
import eejMobileRouter from "./eej-mobile.js";
import eejAuthRouter from "./eej-auth.js";
import jobsRouter from "./jobs.js";
import interviewsRouter from "./interviews.js";
import invoicesRouter from "./invoices.js";
import contractsRouter from "./contracts.js";
import gdprRouter from "./gdpr.js";
import billingRouter from "./billing.js";
import gpsRouter from "./gps.js";
import agencyRouter from "./agency.js";
import regulatoryRouter from "./regulatory.js";
import permitsRouter from "./permits.js";

const router: IRouter = Router();

router.use(eejAuthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(complianceRouter);
router.use(portalRouter);
router.use(auditRouter);
router.use(payrollRouter);
router.use(clientsRouter);
router.use(twofaRouter);
router.use(notificationsRouter);
router.use(workerNotesRouter);
router.use(healthRouter);
router.use(workersRouter);
router.use(eejMobileRouter);
router.use(jobsRouter);
router.use(interviewsRouter);
router.use(invoicesRouter);
router.use(contractsRouter);
router.use(gdprRouter);
router.use(billingRouter);
router.use(gpsRouter);
router.use(agencyRouter);
router.use(regulatoryRouter);
router.use(permitsRouter);

export default router;
