import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import workersRouter from "./workers.js";
import authRouter from "./auth.js";
import adminRouter from "./admin.js";
import complianceRouter from "./compliance.js";
import portalRouter from "./portal.js";
import auditRouter from "./audit.js";
import payrollRouter from "./payroll.js";
import clientsRouter from "./clients.js";
import { twofaRouter } from "./twofa.js";
import notificationsRouter from "./notifications.js";
import workerNotesRouter from "./worker-notes.js";
import eejMobileRouter from "./eej-mobile.js";
import eejAuthRouter from "./eej-auth.js";
import jobsRouter from "./jobs.js";
import interviewsRouter from "./interviews.js";
import invoicesRouter from "./invoices.js";
import contractsRouter from "./contracts.js";
import gdprRouter from "./gdpr.js";
import billingRouter from "./billing.js";
import gpsRouter from "./gps.js";
import agencyRouter from "./agency.js";
import regulatoryRouter from "./regulatory.js";
import permitsRouter from "./permits.js";
import trcServiceRouter from "./trc-service.js";
import seedRouter from "./seed.js";
import revenueRouter from "./revenue.js";
import legalEngineRouter from "../services/legal-engine.js";
import immigrationServiceRouter from "../services/immigration.service.js";
import documentOcrRouter from "../services/document-ocr.js";
import legalKbRouter from "../services/legal-kb.service.js";
import contractEngineRouter from "../services/contract-engine.js";
import legalOperationsRouter from "../services/legal-operations.js";
import testSafetyRouter from "../services/test-safety.js";
import platformFeaturesRouter from "../services/platform-features.js";
import workerTimelineRouter from "../services/worker-timeline.js";
import authorityPacksRouter from "../services/authority-packs.js";
import finesPreventionRouter from "../services/fines-prevention.js";
import tier2Router from "../services/tier2-features.js";
import smartDocRouter from "../services/smart-document.js";
import legalCompletionsRouter from "../services/legal-completions.js";
import caseEngineRouter from "../services/case-engine.js";
import consistencyRouter from "../services/consistency-checker.js";
import communicationRouter from "../services/communication.js";
import documentHardeningRouter from "../services/document-hardening.js";
import enhancedScanRouter from "../services/enhanced-daily-scan.js";
import mosEngineRouter from "../services/mos-engine.js";
import legalBriefRouter from "../services/legal-brief-pipeline.js";
import templateSuggestionRouter from "../services/template-suggestion.js";
import workingDocsRouter from "../services/working-documents.js";
import documentLoggingRouter from "../services/document-logging.js";
import domainSeparationRouter from "../services/domain-separation.js";
import legalTrackingCardRouter from "../services/legal-tracking-card.js";
import researchWorkspaceRouter from "../services/research-workspace.js";
import legalIntelligenceRouter from "../services/legal-intelligence.js";
import smartIngestRouter from "../services/smart-ingest.js";
import legalAnswerRouter from "../services/legal-answer-engine.js";
import knowledgeGraphRouter from "../services/knowledge-graph.js";
import intelligenceRouterService from "../services/intelligence-router.js";
import mosPackageRouter from "../services/mos-package.js";
import schengenRouter from "../services/schengen-calculator.js";
import digitalSafeRouter from "../services/digital-safe.js";
import mos2026Router from "../services/mos-2026-mandate.js";
import firstContactRouter from "../services/first-contact-verification.js";
import notificationEngineRouter from "../services/notification-engine.js";
import escalationEngineRouter from "../services/escalation-engine.js";
import stripeWebhooksRouter from "../services/stripe-webhooks.js";

const router: IRouter = Router();

router.use(eejAuthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(complianceRouter);
router.use(portalRouter);
router.use(auditRouter);
router.use(payrollRouter);
router.use(clientsRouter);
router.use(twofaRouter);
router.use(notificationsRouter);
router.use(workerNotesRouter);
router.use(healthRouter);
router.use(workersRouter);
router.use(eejMobileRouter);
router.use(jobsRouter);
router.use(interviewsRouter);
router.use(invoicesRouter);
router.use(contractsRouter);
router.use(gdprRouter);
router.use(billingRouter);
router.use(gpsRouter);
router.use(agencyRouter);
router.use(regulatoryRouter);
router.use(permitsRouter);
router.use(trcServiceRouter);
router.use(seedRouter);
router.use(revenueRouter);
router.use(legalEngineRouter);
router.use(immigrationServiceRouter);
router.use(documentOcrRouter);
router.use(legalKbRouter);
router.use(contractEngineRouter);
router.use(legalOperationsRouter);
router.use(testSafetyRouter);
router.use(platformFeaturesRouter);
router.use(workerTimelineRouter);
router.use(authorityPacksRouter);
router.use(finesPreventionRouter);
router.use(tier2Router);
router.use(smartDocRouter);
router.use(legalCompletionsRouter);
router.use(caseEngineRouter);
router.use(consistencyRouter);
router.use(communicationRouter);
router.use(documentHardeningRouter);
router.use(enhancedScanRouter);
router.use(mosEngineRouter);
router.use(legalBriefRouter);
router.use(templateSuggestionRouter);
router.use(workingDocsRouter);
router.use(documentLoggingRouter);
router.use(domainSeparationRouter);
router.use(legalTrackingCardRouter);
router.use(researchWorkspaceRouter);
router.use(legalIntelligenceRouter);
router.use(smartIngestRouter);
router.use(legalAnswerRouter);
router.use(knowledgeGraphRouter);
router.use(intelligenceRouterService);
router.use(mosPackageRouter);
router.use(schengenRouter);
router.use(digitalSafeRouter);
router.use(mos2026Router);
router.use(firstContactRouter);
router.use(notificationEngineRouter);
router.use(escalationEngineRouter);
router.use(stripeWebhooksRouter);

// PIP readiness — dynamic import to avoid top-level await in CJS
import("./pip-readiness.js").then(m => router.use(m.default)).catch(() => { /* optional module */ });

export default router;
