/**
 * Word Export — generates .doc files from legal output content.
 *
 * Uses HTML-to-Word approach (no external dependencies).
 * Produces .doc files that open in MS Word, LibreOffice, Google Docs.
 * Preserves Polish characters (UTF-8 charset declaration).
 */

interface WordExportOptions {
  title: string;
  contentPl: string;
  contentEn?: string;
  isDraft?: boolean;
  approvedBy?: string;
  approvedAt?: string;
  generatedAt?: string;
  documentType?: string;
  workerName?: string;
}

/**
 * Export legal content as a .doc file.
 * Opens browser download dialog immediately.
 */
export function exportToWord(options: WordExportOptions): void {
  const {
    title,
    contentPl,
    contentEn,
    isDraft = true,
    approvedBy,
    approvedAt,
    generatedAt,
    documentType,
    workerName,
  } = options;

  const statusLabel = isDraft
    ? "PROJEKT / DRAFT — Requires review before use"
    : approvedBy
      ? `APPROVED by ${approvedBy}${approvedAt ? ` on ${new Date(approvedAt).toLocaleDateString("en-GB")}` : ""}`
      : "REVIEWED";

  const statusColor = isDraft ? "#92400e" : "#166534";
  const statusBg = isDraft ? "#fef3c7" : "#dcfce7";

  const html = `
<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<meta name="ProgId" content="Word.Document">
<title>${escapeHtml(title)}</title>
<style>
  body {
    font-family: 'Calibri', 'Segoe UI', sans-serif;
    font-size: 11pt;
    color: #1e293b;
    line-height: 1.6;
    max-width: 700px;
    margin: 0 auto;
    padding: 40px 20px;
  }
  .status-badge {
    background: ${statusBg};
    border: 1px solid ${statusColor};
    padding: 6px 12px;
    border-radius: 4px;
    font-size: 9pt;
    font-weight: bold;
    color: ${statusColor};
    margin-bottom: 16px;
    display: inline-block;
  }
  h1 {
    font-size: 16pt;
    border-bottom: 2px solid #c41e18;
    padding-bottom: 8px;
    margin-bottom: 16px;
    color: #1e293b;
  }
  .meta {
    font-size: 9pt;
    color: #64748b;
    margin-bottom: 16px;
  }
  .meta span { margin-right: 16px; }
  .content {
    white-space: pre-wrap;
    font-family: 'Courier New', monospace;
    font-size: 10pt;
    line-height: 1.7;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    padding: 16px;
    border-radius: 4px;
    margin-bottom: 24px;
  }
  .section-label {
    font-size: 9pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #64748b;
    margin-bottom: 6px;
    margin-top: 24px;
  }
  .footer {
    margin-top: 40px;
    font-size: 8pt;
    color: #94a3b8;
    text-align: center;
    border-top: 1px solid #e2e8f0;
    padding-top: 12px;
  }
</style>
</head>
<body>
  <div class="status-badge">${escapeHtml(statusLabel)}</div>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">
    ${documentType ? `<span>Type: ${escapeHtml(documentType)}</span>` : ""}
    ${workerName ? `<span>Worker: ${escapeHtml(workerName)}</span>` : ""}
    ${generatedAt ? `<span>Generated: ${new Date(generatedAt).toLocaleDateString("en-GB")}</span>` : `<span>Generated: ${new Date().toLocaleDateString("en-GB")}</span>`}
  </div>
  <div class="section-label">Polish Version / Wersja Polska</div>
  <div class="content">${escapeHtml(contentPl)}</div>
  ${contentEn ? `
  <div class="section-label">English Translation</div>
  <div class="content">${escapeHtml(contentEn)}</div>
  ` : ""}
  <div class="footer">
    Generated by Apatris Legal Intelligence &middot; ${isDraft ? "DRAFT" : "APPROVED"} &middot; ${new Date().toLocaleDateString("en-GB")}
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "application/msword;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = sanitizeFilename(title) + ".doc";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function sanitizeFilename(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9ąćęłńóśźżĄĆĘŁŃÓŚŹŻ\s\-_]/g, "")
    .replace(/\s+/g, "_")
    .substring(0, 80)
    .toLowerCase();
}
